--================= st_categories ===========================
INSERT INTO `categories`(`name`) VALUES
('LABELS ET DIÈTES'),
('LIEU DE PRODUCTION'),
('ORIGINE DES FÈVES'),
('TYPE DE CHOCOLAT'),
('ARTISANAL'),
('BEAN TO BAR'),
('BIO'),
('CRU / NON-CONCHÉ'),
('ÉQUITABLE'),
('EXCLUSIF'),
('SANS SUCRE'),
('VEGAN'),
('ALLEMAGNE'),
('BELGIQUE'),
('CANADA'),
('ESPAGNE'),
('FINLANDE'),
('FRANCE'),
('ISLANDE'),
('SUISSE'),
('USA'),
('BELIZE'),
('BRÉSIL'),
('CAMEROUN'),
('COLOMBIE'),
('CONGO'),
('COSTA RICA'),
('CUBA'),
('ÉQUATEUR'),
('HONDURAS'),
('INDE'),
('JAMAÏQUE'),
('MADAGASCAR'),
('MEXIQUE'),
('NICARAGUA'),
('PAPOUASIE-NOUVELLE-GUINÉE'),
('PÉROU'),
('RÉPUBLIQUE DOMINICAINE'),
('TANZANIE'),
('VENEZUELA'),
('VIETNAM'),
('AU LAIT'),
('BLANC'),
('BLOND'),
('NOIR'),
('NOIR D’ORIGINE'),
('NOIR GRAND CRU '),
('RUBIS');

--================= st_products ===========================
